"use strict";

const DEFAULT_FAST_POLL_INTERVAL = 35000;
const DEFAULT_POLL_INTERVAL = 70000;
const DEFAULT_SLOW_POLL_INTERVAL = 600000;
const DEFAULT_REQUEST_TIMEOUT = 7000;
const DEFAULT_MAX_RETRIES = 3;
const REQUEST_ID_WRAP = 65535;

module.exports = {
	DEFAULT_FAST_POLL_INTERVAL,
	DEFAULT_POLL_INTERVAL,
	DEFAULT_SLOW_POLL_INTERVAL,
	DEFAULT_REQUEST_TIMEOUT,
	DEFAULT_MAX_RETRIES,
	REQUEST_ID_WRAP,
};
