/* eslint-disable no-undef */
/* exported systemDictionary */
systemDictionary = {
	'marstek-venus settings': {
		en: 'Marstek Venus settings',
		de: 'Marstek Venus Einstellungen',
		ru: 'Настройки Marstek Venus',
		pt: 'Configurações do Marstek Venus',
		nl: 'Marstek Venus instellingen',
		fr: 'Paramètres Marstek Venus',
		it: 'Impostazioni Marstek Venus',
		es: 'Configuración de Marstek Venus',
		pl: 'Ustawienia Marstek Venus',
		uk: 'Налаштування Marstek Venus',
		'zh-cn': 'Marstek Venus 设置',
	},
	ipAddress: {
		en: 'Device IP Address',
		de: 'Geräte IP Adresse',
		ru: 'IP-адрес устройства',
		pt: 'Endereço IP do dispositivo',
		nl: 'Apparaat IP-adres',
		fr: 'Adresse IP de l\'appareil',
		it: 'Indirizzo IP del dispositivo',
		es: 'Dirección IP del dispositivo',
		pl: 'Adres IP urządzenia',
		uk: 'IP-адреса пристрою',
		'zh-cn': '设备 IP 地址',
	},
	udpPort: {
		en: 'UDP Port',
		de: 'UDP Port',
		ru: 'UDP-порт',
		pt: 'Porta UDP',
		nl: 'UDP-poort',
		fr: 'Port UDP',
		it: 'Porta UDP',
		es: 'Puerto UDP',
		pl: 'Port UDP',
		uk: 'UDP-порт',
		'zh-cn': 'UDP 端口',
	},
	pollInterval: {
		en: 'Poll interval (ms)',
		de: 'Abfrageintervall (ms)',
		ru: 'Интервал опроса (мс)',
		pt: 'Intervalo de polling (ms)',
		nl: 'Polling-interval (ms)',
		fr: 'Intervalle d\'interrogation (ms)',
		it: 'Intervallo di polling (ms)',
		es: 'Intervalo de consulta (ms)',
		pl: 'Interwał odpytywania (ms)',
		uk: 'Інтервал опитування (мс)',
		'zh-cn': '轮询间隔 (ms)',
	},
	autoDiscovery: {
		en: 'Auto discover devices',
		de: 'Geräte automatisch erkennen',
		ru: 'Автообнаружение устройств',
		pt: 'Descobrir dispositivos automaticamente',
		nl: 'Apparaten automatisch detecteren',
		fr: 'Découverte automatique des appareils',
		it: 'Rilevamento automatico dei dispositivi',
		es: 'Auto-detectar dispositivos',
		pl: 'Automatyczne wykrywanie urządzeń',
		uk: 'Автоматичне виявлення пристроїв',
		'zh-cn': '自动发现设备',
	},
	ipAddress_help: {
		en: 'Leave empty to use auto-discovery, or enter the device\'s IP address if known',
		de: 'Leer lassen um automatische Erkennung zu verwenden, oder geben Sie die IP-Adresse des Geräts ein, falls bekannt',
		ru: 'Оставьте пустым для использования автообнаружения, или введите IP-адрес устройства, если он известен',
		pt: 'Deixe vazio para usar a descoberta automática, ou insira o endereço IP do dispositivo se conhecido',
		nl: 'Laat leeg om automatische detectie te gebruiken, of voer het IP-adres van het apparaat in indien bekend',
		fr: 'Laissez vide pour utiliser la découverte automatique, ou entrez l\'adresse IP de l\'appareil si elle est connue',
		it: 'Lascia vuoto per utilizzare il rilevamento automatico, oppure inserisci l\'indirizzo IP del dispositivo se noto',
		es: 'Dejar vacío para usar el descubrimiento automático, o ingrese la dirección IP del dispositivo si se conoce',
		pl: 'Pozostaw puste, aby użyć automatycznego wykrywania lub wprowadź adres IP urządzenia, jeśli jest znany',
		uk: 'Залиште порожнім для використання автовиявлення, або введіть IP-адресу пристрою, якщо вона відома',
		'zh-cn': '留空以使用自动发现，或输入设备 IP 地址（如果已知）',
	},
	udpPort_help: {
		en: 'UDP port for communication with the device (default 30000, must match the port configured in the Marstek mobile app)',
		de: 'UDP-Port für die Kommunikation mit dem Gerät (Standard 30000, muss mit dem in der Marstek-Mobile-App konfigurierten Port übereinstimmen)',
		ru: 'UDP-порт для связи с устройством (по умолчанию 30000, должен совпадать с портом, настроенным в мобильном приложении Marstek)',
		pt: 'Porta UDP para comunicação com o dispositivo (padrão 30000, deve corresponder à porta configurada no aplicativo móvel Marstek)',
		nl: 'UDP-poort voor communicatie met het apparaat (standaard 30000, moet overeenkomen met de poort geconfigureerd in de Marstek mobiele app)',
		fr: 'Port UDP pour la communication avec l\'appareil (par défaut 30000, doit correspondre au port configuré dans l\'application mobile Marstek)',
		it: 'Porta UDP per la comunicazione con il dispositivo (default 30000, deve corrispondere alla porta configurata nell\'app mobile Marstek)',
		es: 'Puerto UDP para comunicación con el dispositivo (predeterminado 30000, debe coincidir con el puerto configurado en la aplicación móvil Marstek)',
		pl: 'Port UDP do komunikacji z urządzeniem (domyślnie 30000, musi odpowiadać portowi skonfigurowanemu w aplikacji mobilnej Marstek)',
		uk: 'UDP-порт для зв\'язку з пристроєм (за замовчуванням 30000, має відповідати порту, налаштованому в мобільному додатку Marstek)',
		'zh-cn': '用于与设备通信的 UDP 端口（默认 30000，必须与 Marstek 手机应用中配置的端口匹配）',
	},
	pollInterval_help: {
		en: 'How often to query the device for data (lower values for more real-time updates, higher for less device load)',
		de: 'Wie oft das Gerät nach Daten abgefragt wird (niedrigere Werte für Echtzeit-Updates, höhere für geringere Gerätebelastung)',
		ru: 'Как часто опрашивать устройство для получения данных (меньшие значения для более быстрых обновлений, большие для меньшей нагрузки на устройство)',
		pt: 'Com que frequência consultar o dispositivo para dados (valores mais baixos para atualizações mais em tempo real, mais altos para menor carga do dispositivo)',
		nl: 'Hoe vaak het apparaat wordt opgevraagd voor gegevens (lagere waarden voor realtime-updates, hogere voor minder belasting van het apparaat)',
		fr: 'Fréquence de requête des données de l\'appareil (valeurs plus basses pour des mises à jour plus en temps réel, plus élevées pour une charge réduite de l\'appareil)',
		it: 'Con quale frequenza interrogare il dispositivo per i dati (valori più bassi per aggiornamenti più in tempo reale, più alti per un carico minore del dispositivo)',
		es: 'Con qué frecuencia consultar el dispositivo para datos (valores más bajos para actualizaciones más en tiempo real, más altos para menor carga del dispositivo)',
		pl: 'Jak często odpytywać urządzenie o dane (niższe wartości dla bardziej aktualnych danych, wyższe dla mniejszego obciążenia urządzenia)',
		uk: 'Як часто опитувати пристрій для отримання даних (менші значення для більш актуальних оновлень, більші для меншого навантаження на пристрій)',
		'zh-cn': '查询设备的频率（较低值获得更实时的更新，较高值减少设备负载）',
	},
	fastPollInterval: {
		en: 'Fast poll interval (ms) - power values',
		de: 'Schnelles Abfrageintervall (ms) - Leistungswerte',
		ru: 'Быстрый интервал опроса (мс) - значения мощности',
		pt: 'Intervalo de polling rápido (ms) - valores de energia',
		nl: 'Snel polling-interval (ms) - vermogenswaarden',
		fr: 'Intervalle d\'interrogation rapide (ms) - valeurs de puissance',
		it: 'Intervallo di polling veloce (ms) - valori di potenza',
		es: 'Intervalo de consulta rápido (ms) - valores de potencia',
		pl: 'Szybki interwał odpytywania (ms) - wartości mocy',
		uk: 'Швидкий інтервал опитування (мс) - значення потужності',
		'zh-cn': '快速轮询间隔 (ms) - 功率值',
	},
	fastPollInterval_help: {
		en: 'How often to query power values (pv, grid, battery, load). Lower values = faster updates for power data',
		de: 'Wie oft Leistungswerte abgefragt werden (pv, grid, battery, load). Niedrigere Werte = schnellere Updates für Leistungsdaten',
		ru: 'Как часто запрашивать значения мощности (pv, grid, battery, load). Меньшие значения = более быстрые обновления данных о мощности',
		pt: 'Com que frequência consultar valores de energia (pv, grid, battery, load). Valores mais baixos = atualizações mais rápidas para dados de energia',
		nl: 'Hoe vaak vermogenswaarden opvragen (pv, grid, battery, load). Lagere waarden = snellere updates voor vermogensgegevens',
		fr: 'Fréquence de requête des valeurs de puissance (pv, grid, battery, load). Valeurs plus basses = mises à jour plus rapides pour les données de puissance',
		it: 'Con quale frequenza interrogare i valori di potenza (pv, grid, battery, load). Valori più bassi = aggiornamenti più rapidi per i dati di potenza',
		es: 'Con qué frecuencia consultar valores de energía (pv, grid, battery, load). Valores más bajos = actualizaciones más rápidas para datos de energía',
		pl: 'Jak często odpytywać wartości mocy (pv, grid, battery, load). Niższe wartości = szybsze aktualizacje danych o mocy',
		uk: 'Як часто запитувати значення потужності (pv, grid, battery, load). Менші значення = швидші оновлення даних про потужність',
		'zh-cn': '查询功率值的频率（pv、grid、battery、load）。值越低，功率数据更新越快',
	},
	requestTimeout: {
		en: 'Request timeout (ms)',
		de: 'Anfrage-Timeout (ms)',
		ru: 'Тайм-аут запроса (мс)',
		pt: 'Tempo limite da solicitação (ms)',
		nl: 'Verzoek time-out (ms)',
		fr: 'Délai d\'attente de la requête (ms)',
		it: 'Timeout della richiesta (ms)',
		es: 'Tiempo de espera de la solicitud (ms)',
		pl: 'Limit czasu żądania (ms)',
		uk: 'Тайм-аут запиту (мс)',
		'zh-cn': '请求超时 (ms)',
	},
	requestTimeout_help: {
		en: 'How long to wait for a response before retrying (higher for slow devices)',
		de: 'Wie lange auf eine Antwort gewartet wird, bevor erneut versucht wird (höher für langsame Geräte)',
		ru: 'Как долго ждать ответа перед повторной попыткой (больше для медленных устройств)',
		pt: 'Quanto tempo esperar por uma resposta antes de tentar novamente (maior para dispositivos lentos)',
		nl: 'Hoe lang wachten op een antwoord voordat opnieuw wordt geprobeerd (hoger voor langzame apparaten)',
		fr: 'Durée d\'attente d\'une réponse avant de réessayer (plus élevé pour les appareils lents)',
		it: 'Quanto tempo aspettare una risposta prima di riprovare (più alto per i dispositivi lenti)',
		es: 'Cuánto tiempo esperar una respuesta antes de reintentar (mayor para dispositivos lentos)',
		pl: 'Jak długo czekać na odpowiedź przed ponowieniem próby (wyższe dla wolnych urządzeń)',
		uk: 'Як довго чекати на відповідь перед повторною спробою (більше для повільних пристроїв)',
		'zh-cn': '等待响应的时间，然后重试（对于慢设备使用更高的值）',
	},
	maxRetries: {
		en: 'Max retries per request',
		de: 'Max. Wiederholungen pro Anfrage',
		ru: 'Макс. повторов на запрос',
		pt: 'Máximo de tentativas por solicitação',
		nl: 'Max. nieuwe pogingen per verzoek',
		fr: 'Tentatives max par requête',
		it: 'Massimo di tentativi per richiesta',
		es: 'Máximo de reintentos por solicitud',
		pl: 'Maksymalna liczba ponownych prób na żądanie',
		uk: 'Макс. повторів на запит',
		'zh-cn': '每次请求的最大重试次数',
	},
	maxRetries_help: {
		en: 'Number of retry attempts if a request times out (0 = no retries)',
		de: 'Anzahl der Wiederholungsversuche bei Timeout (0 = keine Wiederholungen)',
		ru: 'Количество попыток повтора при тайм-ауте запроса (0 = без повторов)',
		pt: 'Número de tentativas de repetição se uma solicitação expirar (0 = sem repetições)',
		nl: 'Aantal hernieuwingspogingen als een verzoek time-out (0 = geen nieuwe pogingen)',
		fr: 'Nombre de tentatives de réessai en cas de délai d\'expiration de la requête (0 = pas de réessai)',
		it: 'Numero di tentativi di ripetizione se una richiesta scade (0 = nessun tentativo)',
		es: 'Número de intentos de reintento si una solicitud se agota (0 = sin reintentos)',
		pl: 'Liczba prób ponownych, jeśli żądanie przekroczy limit czasu (0 = brak ponownych prób)',
		uk: 'Кількість спроб повтору у разі тайм-ауту запиту (0 = без повторів)',
		'zh-cn': '请求超时时重试的次数（0 = 不重试）',
	},
	autoDiscovery_help: {
		en: 'Enable automatic device discovery on the local network (recommended for first-time setup)',
		de: 'Automatische Geräteerkennung im lokalen Netzwerk aktivieren (empfohlen für die Ersteinrichtung)',
		ru: 'Включить автоматическое обнаружение устройств в локальной сети (рекомендуется для первоначальной настройки)',
		pt: 'Ativar a descoberta automática de dispositivos na rede local (recomendado para configuração inicial)',
		nl: 'Automatische apparaatdetectie op het lokale netwerk inschakelen (aanbevolen voor eerste installatie)',
		fr: 'Activer la découverte automatique des appareils sur le réseau local (recommandé pour la configuration initiale)',
		it: 'Abilitare il rilevamento automatico dei dispositivi sulla rete locale (consigliato per la configurazione iniziale)',
		es: 'Habilitar el descubrimiento automático de dispositivos en la red local (recomendado para la configuración inicial)',
		pl: 'Włącz automatyczne wykrywanie urządzeń w sieci lokalnej (zalecane przy pierwszej konfiguracji)',
		uk: 'Увімкнути автоматичне виявлення пристроїв у локальній мережі (рекомендовано для початкового налаштування)',
		'zh-cn': '在本地网络上启用自动设备发现（首次设置时推荐）',
	},
	discover: {
		en: 'Discover devices',
		de: 'Geräte suchen',
		ru: 'Найти устройства',
		pt: 'Descobrir dispositivos',
		nl: 'Apparaten detecteren',
		fr: 'Découvrir les appareils',
		it: 'Scopri dispositivi',
		es: 'Descubrir dispositivos',
		pl: 'Wykryj urządzenia',
		uk: 'Виявити пристрої',
		'zh-cn': '发现设备',
	},
};